/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 black_belt.glb -T
Files: black_belt.glb [8.7MB] > /Users/yegor-nextcode/Invitus/web/invitus/public/assets/models/black_belt-transformed.glb [199.05KB] (98%)
*/

import { useGLTF } from '@react-three/drei'

export function BlackBeltModel(props) {
  const { nodes, materials } = useGLTF('/models/black_belt-transformed.glb')

  return (
    <group {...props} dispose={null}>
      <group scale={2.5}>
        <mesh geometry={nodes.BLACK_BELT_1.geometry} material={materials.BLACK_BELT} />
        <mesh geometry={nodes.BLACK_BELT_2.geometry} material={materials.DETAILS} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/black_belt-transformed.glb')
